### ISSUE TITLE
Failed to login to admin page

### ISSUE THREAD

**Issue by raccoon2k** [arifulislamarif/ogani#1]
Hi, i try to reproduce your app without any tweak, but i think i missed something.
My problem is when I try to login with a email and password for the admin page (admin@gmail.com - 00000000), I get the following error:
These credentials do not match our records. 
I seeded the data , and admin@gmail.com created in admins table
is there anything i can do to fix it ?
Thank you.

**Comment by devxarif** [comment]
Hello, Nguyễn Tuấn Anh
Thanks for reaching out. I will solve the problem by checking. I will let you know after I fix the problem.
Thank you
